# docker-compose.yml
version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: nobel-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nobel-app
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - ./app.py:/app/app.py:ro
      - ./ingest.py:/app/ingest.py:ro
      - ./requirements.txt:/app/requirements.txt:ro

volumes:
  mongo_data:
